title: Programming: Principles and Practice Using C++
description: 
show_downloads: false
git_branch: master
logo_url: https://github.com/cppWarrior/Wiki/blob/master/assets/images/ppp.jpg
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
